name: Weekly Python Tasks (Linux)

permissions:
  contents: read
  pages: write
  id-token: write

on:
  schedule:
    - cron: '0 18 * * 1'  # every Sunday at midnight UTC
  workflow_dispatch:  # optional manual trigger

jobs:
  run-linux-scripts:
    runs-on: ubuntu-latest
    env:
      FACEIT_API_KEY: ${{ secrets.FACEIT_API_KEY }}

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3
      
      # 3️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5️⃣ Run sync.py
      - name: Run sync.py
        run: |
          echo "[1/2] Running sync.py..."
          python sync.py
        shell: bash
        continue-on-error: false

      # 6️⃣ Run html_gen.py
      - name: Run html_gen.py
        run: |
          echo "[2/2] Generating HTML..."
          python html_gen.py
        shell: bash
        continue-on-error: false

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4                

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
